"""
run_analysis.py  --  STEP 3: run the six queries and export chart CSVs.

analysis.sql is the single source of truth. This runner just:
  1. splits it on the "-- QUERY: id | title | export=file" marker lines,
  2. runs each query against readmissions.db,
  3. prints the result as a small table,
  4. writes the CSV named in the marker into exports/ (unless export=-).

Keeping the SQL in a .sql file (not in Python strings) means a reviewer can
read or re-run it in DB Browser exactly as shipped.

Run:
    python3 run_analysis.py
Needs: nothing but the standard library (sqlite3, csv).
"""

import csv
import json
import os
import re
import sqlite3
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(HERE, "readmissions.db")
SQL_PATH = os.path.join(HERE, "analysis.sql")
EXPORTS = os.path.join(HERE, "exports")
DASHBOARD = os.path.join(HERE, "dashboard")
os.makedirs(EXPORTS, exist_ok=True)
os.makedirs(DASHBOARD, exist_ok=True)

MARKER = re.compile(r"--\s*QUERY:\s*(\S+)\s*\|\s*(.+?)\s*\|\s*export=(\S+)\s*$")


def parse_queries(sql_text):
    """Yield (id, title, export, sql) for each marked query block."""
    blocks = []
    current = None
    body = []
    for line in sql_text.splitlines():
        m = MARKER.match(line.strip())
        if m:
            if current:
                blocks.append((*current, "\n".join(body).strip()))
            current = (m.group(1), m.group(2), m.group(3))
            body = []
        elif current is not None:
            body.append(line)
    if current:
        blocks.append((*current, "\n".join(body).strip()))
    return blocks


def print_table(headers, rows, max_rows=12):
    widths = [len(h) for h in headers]
    shown = rows[:max_rows]
    for r in shown:
        for i, v in enumerate(r):
            widths[i] = max(widths[i], len(str(v)))
    line = "  ".join(h.ljust(widths[i]) for i, h in enumerate(headers))
    print("    " + line)
    print("    " + "  ".join("-" * widths[i] for i in range(len(headers))))
    for r in shown:
        print("    " + "  ".join(str(v).ljust(widths[i])
                                 for i, v in enumerate(r)))
    if len(rows) > max_rows:
        print(f"    ... ({len(rows) - max_rows} more rows in the CSV)")


def size_band(discharges):
    if discharges is None:
        return None
    if discharges < 100:
        return "Small (<100)"
    if discharges < 300:
        return "Medium (100-299)"
    if discharges < 600:
        return "Large (300-599)"
    return "Very large (600+)"


def build_dashboard_data(con):
    """
    Write dashboard/data.js with row-level records so the dashboard can
    recompute all four charts for any state (the state filter) in the browser,
    with no server needed. One record per (hospital, condition) with a numeric
    ERR. Columns kept short to keep the file small.
    """
    rows = con.execute("""
        SELECT state, condition, hospital_ownership, star_rating,
               number_of_discharges, excess_readmission_ratio
        FROM joined
        WHERE excess_readmission_ratio IS NOT NULL
    """).fetchall()

    records = []
    for state, cond, own, star, disc, err in rows:
        records.append([
            state, cond, own,
            int(star) if star is not None else None,
            size_band(disc),
            round(err, 4),
        ])

    payload = {
        "columns": ["state", "condition", "ownership", "star",
                    "size_band", "err"],
        "records": records,
    }
    path = os.path.join(DASHBOARD, "data.js")
    with open(path, "w") as f:
        f.write("// Auto-generated by run_analysis.py -- do not edit by hand.\n")
        f.write("window.DASHBOARD_DATA = ")
        json.dump(payload, f, separators=(",", ":"))
        f.write(";\n")
    print(f"\n    -> dashboard/data.js ({len(records):,} records embedded)")


def main():
    if not os.path.exists(DB_PATH):
        sys.exit("readmissions.db not found. Run: python3 clean.py")

    with open(SQL_PATH) as f:
        queries = parse_queries(f.read())

    con = sqlite3.connect(DB_PATH)
    for qid, title, export, sql in queries:
        print(f"\n[{qid}] {title}")
        cur = con.execute(sql)
        headers = [d[0] for d in cur.description]
        rows = cur.fetchall()
        print_table(headers, rows)

        if export and export != "-":
            path = os.path.join(EXPORTS, export)
            with open(path, "w", newline="") as f:
                w = csv.writer(f)
                w.writerow(headers)
                w.writerows(rows)
            print(f"    -> exports/{export}")
    build_dashboard_data(con)
    con.close()
    print("\nDone. CSVs are in exports/ for Tableau.")
    print("Open dashboard/index.html (double-click) to see the charts.")


if __name__ == "__main__":
    main()
